<?php

/**
 * BaseProjetEventCom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property string $commentaire
 * @property enum $statut
 * @property integer $membre_id
 * @property integer $projet_event_id
 * @property ProjetEvent $ProjetEvent
 * @property Membre $Membre
 * 
 * @method date           getDate()            Returns the current record's "date" value
 * @method string         getCommentaire()     Returns the current record's "commentaire" value
 * @method enum           getStatut()          Returns the current record's "statut" value
 * @method integer        getMembreId()        Returns the current record's "membre_id" value
 * @method integer        getProjetEventId()   Returns the current record's "projet_event_id" value
 * @method ProjetEvent    getProjetEvent()     Returns the current record's "ProjetEvent" value
 * @method Membre         getMembre()          Returns the current record's "Membre" value
 * @method ProjetEventCom setDate()            Sets the current record's "date" value
 * @method ProjetEventCom setCommentaire()     Sets the current record's "commentaire" value
 * @method ProjetEventCom setStatut()          Sets the current record's "statut" value
 * @method ProjetEventCom setMembreId()        Sets the current record's "membre_id" value
 * @method ProjetEventCom setProjetEventId()   Sets the current record's "projet_event_id" value
 * @method ProjetEventCom setProjetEvent()     Sets the current record's "ProjetEvent" value
 * @method ProjetEventCom setMembre()          Sets the current record's "Membre" value
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetEventCom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_event_com');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('commentaire', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('statut', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 0.1,
              2 => 0.2,
              3 => 0.3,
              4 => 0.4,
              5 => 0.5,
              6 => 0.6,
              7 => 0.7,
              8 => 0.8,
              9 => 0.9,
              10 => 1,
             ),
             ));
        $this->hasColumn('membre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('projet_event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProjetEvent', array(
             'local' => 'projet_event_id',
             'foreign' => 'id'));

        $this->hasOne('Membre', array(
             'local' => 'membre_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}