<?php

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $is_todo
 * @property integer $membre_id
 * @property date $date_start
 * @property date $date_end
 * @property Membre $Membre
 * @property Doctrine_Collection $EventInvites
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method boolean             getIsTodo()       Returns the current record's "is_todo" value
 * @method integer             getMembreId()     Returns the current record's "membre_id" value
 * @method date                getDateStart()    Returns the current record's "date_start" value
 * @method date                getDateEnd()      Returns the current record's "date_end" value
 * @method Membre              getMembre()       Returns the current record's "Membre" value
 * @method Doctrine_Collection getEventInvites() Returns the current record's "EventInvites" collection
 * @method Event               setTitle()        Sets the current record's "title" value
 * @method Event               setDescription()  Sets the current record's "description" value
 * @method Event               setIsTodo()       Sets the current record's "is_todo" value
 * @method Event               setMembreId()     Sets the current record's "membre_id" value
 * @method Event               setDateStart()    Sets the current record's "date_start" value
 * @method Event               setDateEnd()      Sets the current record's "date_end" value
 * @method Event               setMembre()       Sets the current record's "Membre" value
 * @method Event               setEventInvites() Sets the current record's "EventInvites" collection
 * 
 * @package    Annuaire
 * @subpackage model
 * @author     Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('is_todo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('membre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_start', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_end', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Membre', array(
             'local' => 'membre_id',
             'foreign' => 'id'));

        $this->hasMany('EventInvites', array(
             'local' => 'id',
             'foreign' => 'event_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}