<?php

/**
 * EventInvitesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventInvitesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventInvitesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventInvites');
    }
}