<?php

/**
 * ProjetEventComTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjetEventComTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjetEventComTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjetEventCom');
    }
}