# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: annuaire, action: index }

## Agenda
agenda:
  url: /agenda/:action/*
  param: { module: agenda, action: index }

## Statistiques
stats:
  url: /stats/:action/*
  param: { module: stats, action: index }

### Annuaire
annuaire:
  url: /annuaire/:action/*
  param: { module: annuaire }

annuaire.index:
  url:  /annuaire/
  param: { module: annuaire, action: index }

## Trombinoscope
annuaire.trombi:
  url: /annuaire/trombi/*
  param: { module: annuaire, action: trombi }

## Carte
carte:
  url: /carte/:action/*
  param: { module: carte }

carte.index:
  url:  /carte/
  param: { module: carte, action: index }

## Prospect
prospect:
  url: /prospect/:action/*
  param: { module: prospect }

prospect.index:
  url: /prospect/
  param: { module: prospect, action: index }

## Contact
contact:
  url: /contact/:action/*
  param: { module: contact }

contact.index:
  url: /contact/
  param: { module: contact, action: index }

## Projet
projet:
  url: /projet/:action/*
  param: { module: projet }

projet.index:
  url: /projet/
  param: { module: projet, action: index }

## ProjetEvent
projetevent:
  url: /projetevent/:action/*
  param: { module: projetevent }

projetevent.index:
  url: /projetevent/
  param: { module: projetevent, action: index }

## ProjetEventCom
projeteventcom:
  url: /projeteventcom/:action/*
  param: { module: projeteventcom }

projeteventcom.index:
  url: /projeteventcom/
  param: { module: projeteventcom, action: index }

## ProjetParticipant
projetparticipant:
  url: /projetparticipant/:action/*
  param: { module: projetparticipant }

projetparticipant.index:
  url: /projetparticipant/
  param: { module: projetparticipant, action: index }
  
## Cotisation
cotisation:
  url: /cotisation/:action/*
  param: { module: cotisation }

projetparticipant.index:
  url: /cotisation/
  param: { module: cotisation, action: index }

## Search
search:
  url: /search/*
  param: {module: search, action: index}

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
